services:
  admin:
    build: 
      context: chuoiduahangvai-admin
    ports:
      - 8888:8888
  be:
    build: 
      context: chuoiduahangvai-be
    ports:
      - 1337:1337
  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: chuoicuahangvai-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
