services:
  admin:
    build: 
      context: chuoicuahangvai-admin
    ports:
      - 8888:8888
    depends_on:
      - database
  be:
    build: 
      context: chuoicuahangvai-be
    ports:
      - 1337:1337
    depends_on:
      - database
  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: chuoicuahangvai-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
