services:
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - be
    ports:
      - "1337:1337"

  client:
    build: 
      context: chuoicuahangvai-client
    ports:
      - 80:3000
  
  admin:
    build: 
      context: chuoicuahangvai-admin
    ports:
      - 8888:8888
  
  be:
    build: 
      context: chuoicuahangvai-be
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
    expose:
      - "5000"
  
  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: chuoicuahangvai-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
